spring.application.name=Ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceTest
spring.datasource.username=postgres
spring.datasource.password=password


# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Automatically update database schema (optional, can be changed to 'validate' or 'none' in production)
spring.jpa.hibernate.ddl-auto=update

# Optionally, enable SQL logging (helpful for debugging)
spring.jpa.show-sql=true

# Directory to store uploaded product images
upload.directory=uploads/products/


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=1DAAA1B60A3874F663000FA5E3D892C0E2F41FF93CE111289EB740B00B6D9553
app.jwt.expiration=86400000  # 1 day in milliseconds

#logging.level.org.springframework.security=DEBUG
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE



# Stripe Secret Key
#stripe.secret.key=YOUR_STRIPE_SECRET_KEY



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
